version: '3.8'

services:
  todo-api:
    build: ./
    command: ./wait-for-postgres.sh db ./todo-api
    ports:
      - 8080:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432